app = 'tailscale'
swap_size_mb = 256
primary_region = 'ams'

[mounts]
  source = "tailscale"
  destination = "/data"

[[restart]]
  policy = "always"

[[vm]]
  cpus = 1
  memory_mb = 256
  cpu_kind = 'shared'

[deploy]
  strategy = "immediate"
