app = 'vpn-ps'
primary_region = 'ams'
swap_size_mb = 256

[mounts]
  source = "vpn_data"
  destination = "/data"

[[restart]]
  policy = "always"

[[vm]]
  memory_mb = 256
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "immediate"
