app = 'tailscale'
swap_size_mb = 1024
primary_region = 'ams'

[mounts]
  source = "tailscale"
  destination = "/data"

[[restart]]
  policy = "always"

[[vm]]
  cpus = 1
  memory_mb = 256
  memory = '256mb'
  cpu_kind = 'shared'
  size = 'shared-cpu-1x'
  persist_rootfs = "always"

[deploy]
  strategy = "immediate"
