name: Update policy

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build CIDR and update policy
        run: bun run build.js

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit -am "Update policy.hujson"

      - name: Fetch version-cache.json
        uses: actions/cache@v4
        with:
          path: ./version-cache.json
          key: version-cache.json-${{ github.run_id }}
          restore-keys: |
            version-cache.json-

      - name: Deploy ACL to Tailscale
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ vars.TS_OAUTH_ID }}
          audience: ${{ vars.TS_AUDIENCE }}
          tailnet: ${{ vars.TS_TAILNET }}
          action: apply

      - run: git push
